pipeline {
    agent {
        label 'agent-1'
    }

    parameters {
        string(name: 'DEPLOY_PORT', defaultValue: '9003', description: 'Port to deploy the application')
    }

    environment {
        PROJECT_NAME = "school_timetabling"
        CONTAINER_NAME =  "${PROJECT_NAME}_container"
        IMAGE_NAME = "${PROJECT_NAME}:latest"
        FULL_IMAGE_NAME = "${IMAGE_NAME}"
    }

    stages {
        stage('Building Docker Image') {
            steps {
                script {
                    def image = docker.build("${env.FULL_IMAGE_NAME}", "-f deploy/Dockerfile .")
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh "docker stop ${env.CONTAINER_NAME} || true"
                    sh "docker rm ${env.CONTAINER_NAME} || true"
                    docker.image("${env.FULL_IMAGE_NAME}").run("-p ${params.DEPLOY_PORT}:80 --name ${env.CONTAINER_NAME}")
                }
            }
        }
    }
}